// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyPhuongTienChungCu.Data;

#nullable disable

namespace QuanLyPhuongTienChungCu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910070907_ThemQuanHePhuongTienChoLuotGuiXe")]
    partial class ThemQuanHePhuongTienChoLuotGuiXe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.BangGia", b =>
                {
                    b.Property<long>("BangGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("BangGiaId"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("HieuLucDen")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HieuLucTu")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("LoaiPhuongTienId")
                        .HasColumnType("bigint");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BangGiaId");

                    b.HasIndex("LoaiPhuongTienId");

                    b.ToTable("BangGias");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.LoaiPhuongTien", b =>
                {
                    b.Property<long>("LoaiPhuongTienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("LoaiPhuongTienId"));

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoaiPhuongTienId");

                    b.HasIndex("TenLoai")
                        .IsUnique();

                    b.ToTable("LoaiPhuongTiens");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.LuotGuiXe", b =>
                {
                    b.Property<long>("LuotGuiXeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("LuotGuiXeId"));

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("LoaiPhuongTienId")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("PhuongTienId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("ThoiGianRa")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ThoiGianVao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LuotGuiXeId");

                    b.HasIndex("LoaiPhuongTienId");

                    b.HasIndex("PhuongTienId");

                    b.HasIndex("BienSo", "TrangThai");

                    b.ToTable("LuotGuiXes");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.PhuongTien", b =>
                {
                    b.Property<long>("PhuongTienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("PhuongTienId"));

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("LoaiPhuongTienId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaCanHo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenChuXe")
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PhuongTienId");

                    b.HasIndex("BienSo")
                        .IsUnique();

                    b.HasIndex("LoaiPhuongTienId");

                    b.ToTable("PhuongTiens");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.BangGia", b =>
                {
                    b.HasOne("QuanLyPhuongTienChungCu.Models.LoaiPhuongTien", "LoaiPhuongTien")
                        .WithMany("BangGias")
                        .HasForeignKey("LoaiPhuongTienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhuongTien");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.LuotGuiXe", b =>
                {
                    b.HasOne("QuanLyPhuongTienChungCu.Models.LoaiPhuongTien", "LoaiPhuongTien")
                        .WithMany()
                        .HasForeignKey("LoaiPhuongTienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyPhuongTienChungCu.Models.PhuongTien", "PhuongTien")
                        .WithMany("LuotGuiXes")
                        .HasForeignKey("PhuongTienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiPhuongTien");

                    b.Navigation("PhuongTien");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.PhuongTien", b =>
                {
                    b.HasOne("QuanLyPhuongTienChungCu.Models.LoaiPhuongTien", "LoaiPhuongTien")
                        .WithMany("PhuongTiens")
                        .HasForeignKey("LoaiPhuongTienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhuongTien");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.LoaiPhuongTien", b =>
                {
                    b.Navigation("BangGias");

                    b.Navigation("PhuongTiens");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.PhuongTien", b =>
                {
                    b.Navigation("LuotGuiXes");
                });
#pragma warning restore 612, 618
        }
    }
}
