// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyPhuongTienChungCu.Data;

#nullable disable

namespace QuanLyPhuongTienChungCu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("DoiTuong")
                        .HasColumnType("longtext");

                    b.Property<long?>("DoiTuongId")
                        .HasColumnType("bigint");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ThoiGian");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.BangGia", b =>
                {
                    b.Property<long>("BangGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("BangGiaId"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("HieuLucDen")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HieuLucTu")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("LoaiPhuongTienId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiTinhPhi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BangGiaId");

                    b.HasIndex("LoaiPhuongTienId");

                    b.ToTable("BangGias", (string)null);
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.CanHo", b =>
                {
                    b.Property<long>("CanHoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CanHoId"));

                    b.Property<string>("MaCanHo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SoPhong")
                        .HasColumnType("int");

                    b.Property<int>("Tang")
                        .HasColumnType("int");

                    b.Property<string>("Toa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("CanHoId");

                    b.HasIndex("UserId");

                    b.ToTable("CanHo", (string)null);
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.LoaiPhuongTien", b =>
                {
                    b.Property<long>("LoaiPhuongTienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("LoaiPhuongTienId"));

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoaiPhuongTienId");

                    b.HasIndex("TenLoai")
                        .IsUnique();

                    b.ToTable("LoaiPhuongTiens", (string)null);
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.LuotGuiXe", b =>
                {
                    b.Property<long>("LuotGuiXeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("LuotGuiXeId"));

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("LoaiPhuongTienId")
                        .HasColumnType("bigint");

                    b.Property<long?>("NguoiGhiRaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("NguoiGhiVaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiTaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PhuongTienId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("ThoiGianRa")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ThoiGianVao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LuotGuiXeId");

                    b.HasIndex("LoaiPhuongTienId");

                    b.HasIndex("PhuongTienId");

                    b.HasIndex("BienSo", "TrangThai");

                    b.ToTable("LuotGuiXes", (string)null);
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.PhuongTien", b =>
                {
                    b.Property<long>("PhuongTienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("PhuongTienId"));

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("LoaiPhuongTienId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaCanHo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenChuXe")
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PhuongTienId");

                    b.HasIndex("BienSo")
                        .IsUnique();

                    b.HasIndex("LoaiPhuongTienId");

                    b.HasIndex("UserId");

                    b.ToTable("PhuongTiens", (string)null);
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<string>("TenRole")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("RoleId");

                    b.HasIndex("TenRole")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.ThanhToan", b =>
                {
                    b.Property<long>("ThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ThanhToanId"));

                    b.Property<long>("LuotGuiXeId")
                        .HasColumnType("bigint");

                    b.Property<long>("NguoiThanhToanId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ThoiGianThanhToan")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ThanhToanId");

                    b.HasIndex("LuotGuiXeId")
                        .IsUnique();

                    b.ToTable("ThanhToans", (string)null);
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("CCCD")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.AuditLog", b =>
                {
                    b.HasOne("QuanLyPhuongTienChungCu.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.BangGia", b =>
                {
                    b.HasOne("QuanLyPhuongTienChungCu.Models.LoaiPhuongTien", "LoaiPhuongTien")
                        .WithMany("BangGias")
                        .HasForeignKey("LoaiPhuongTienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhuongTien");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.CanHo", b =>
                {
                    b.HasOne("QuanLyPhuongTienChungCu.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.LuotGuiXe", b =>
                {
                    b.HasOne("QuanLyPhuongTienChungCu.Models.LoaiPhuongTien", "LoaiPhuongTien")
                        .WithMany()
                        .HasForeignKey("LoaiPhuongTienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyPhuongTienChungCu.Models.PhuongTien", "PhuongTien")
                        .WithMany("LuotGuiXes")
                        .HasForeignKey("PhuongTienId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoaiPhuongTien");

                    b.Navigation("PhuongTien");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.PhuongTien", b =>
                {
                    b.HasOne("QuanLyPhuongTienChungCu.Models.LoaiPhuongTien", "LoaiPhuongTien")
                        .WithMany("PhuongTiens")
                        .HasForeignKey("LoaiPhuongTienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyPhuongTienChungCu.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoaiPhuongTien");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.ThanhToan", b =>
                {
                    b.HasOne("QuanLyPhuongTienChungCu.Models.LuotGuiXe", "LuotGuiXe")
                        .WithMany()
                        .HasForeignKey("LuotGuiXeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LuotGuiXe");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.User", b =>
                {
                    b.HasOne("QuanLyPhuongTienChungCu.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.LoaiPhuongTien", b =>
                {
                    b.Navigation("BangGias");

                    b.Navigation("PhuongTiens");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.PhuongTien", b =>
                {
                    b.Navigation("LuotGuiXes");
                });

            modelBuilder.Entity("QuanLyPhuongTienChungCu.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
